### PR TITLE
fix bug. default refreshTimeIntervalInMillis is too big and should get from config

### PR DESCRIPTION
**Pull request by shangan**
I did not use the new constructor now which should get value from config param, I'm not sure if I misunderstood something. Currently,SourceKafkaClusterValidationManager, AutoTopicWhitelistingManagern can not get topics info as soon as it expected. If I'm right, I'd like to add a new param in controllerOptions or use refreshTimeInSeconds for common sense.

### CODE REVIEW

**Comment by xhl1988** [comment]
@shangan Nice catch! A param makes more sense. Since you are changing this, I would suggest to help change the constructor so other people can also use it.

**Comment by shangan** [comment]
@xhl1988 I've update the constructor. I prefer to reuse param refreshTimeInSeconds rather than adding a new param, as the cache refresh should be transparent to user. 

And I found another bug as following, I will fix it in another patch

if (cmd.hasOption("refreshTimeInSeconds")) {
      controllerConf.setInitWaitTimeInSeconds(cmd.getOptionValue("refreshTimeInSeconds"));
    } else {
      controllerConf.setInitWaitTimeInSeconds("600");
    }

**Comment by xhl1988** [comment]
lgtm

**Comment by shangan** [comment]
@xhl1988 could you please merge the pr, then we can move forward. Can I have your email, I want to learn something more about this project.

**Comment by xhl1988** [comment]
@shangan Thanks for the contribution. You can contact me at hongxu@uber.com

**Pull request merged**
